<?php

########################################################################
# Extension Manager/Repository config file for ext: "paginate"
#
# Auto generated by Extension Builder 2011-09-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid Pagination',
	'description' => 'Fluid Pagination Widget for many pages',
	'category' => 'plugin',
	'author' => 'Rüdiger Marwein',
	'author_email' => 'ruediger.marwein@googlemail.com',
	'author_company' => '21TORR',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'final',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
